CREATE UNIQUE INDEX IF NOT EXISTS UX_629ab9_Id ON de.AllegedBullyingVictim(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_8fe144_Id ON de.CIPCourse(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_6867fd_Id ON de.DisciplineIncidentCode(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_948884_Id ON de.GradeTypeDetail(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_cf3970_Id ON de.LevelDetail(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_54dd73_Id ON de.MedicalAlert(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_7bbd92_Id ON de.MedicalOfficeVisit(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_d22e7d_Id ON de.MedicalReferralFollowUp(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_afc675_Id ON de.MedicalScreening(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_f55449_Id ON de.MedicationBox(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_8d6131_Id ON de.NonStudent(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_073b20_Id ON de.PersonDisciplineAction(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_fcc994_Id ON de.PersonDisciplineIncidentAssociation(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_f28934_Id ON de.PersonImmunization(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_02d654_Id ON de.PersonMedicalAlert(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_4ee256_Id ON de.PersonMedicationBoxAssociation(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_e1d001_Id ON de.PostSecondaryDetail(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_b9f994_Id ON de.RestraintSeclusion(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_86ec01_Id ON de.StudentSectionClassPeriodAttendanceEvent(Id);

CREATE UNIQUE INDEX IF NOT EXISTS UX_68afad_Id ON de.StudentTransportation(Id);

